export const clients = [
    "161103556337719895.png",
    "Adani_logo_2012.svg.png",
    "Aegis Vopak.png",
    "Agrocel.jfif",
    "Ahlstrom_Logo.png",
    "All india Radio.JPG",
    "Alpha.jpg",
    "Anchor.png",
    "Archean.jpg",
    "Asean Box.jpg",
    "Ashapura China.jfif",
    "Ashapura.jpg",
    "Asti.png",
    "Ayoni.png",
    "BAxter.jpg",
    "BLA Power.jfif",
    "BPCL_400x400.jfif",
    "Biocon.png",
    "CIMS.png",
    "Carrier.png",
    "Chiripal-Poly-Films-Logo1.png",
    "Creative Forges Pvt ltd.jpg",
    "Crystal.JPG",
    "Deepak-Nitrite-Ltd-Logo.png",
    "Dev salt.png",
    "EXL_Service_logo.png",
    "Energy Advisory Services.jpg",
    "Fashion Tech.jfif",
    "GFIPL-FINAL-basic.png",
    "GGL.png",
    "German.png",
    "GujaratMineralDevelopmentCorporationLogo.jpg",
    "HLE.png",
    "HNV.gif",
    "HZL.png",
    "ICA_India_Logo_Copper_RGB-scaled.jpg",
    "IOCL.png",
    "J K Laxmi.png",
    "Jay Jalaram.jfif",
    "Jindal saw Limited.png",
    "Kalyani_Logo.jpg",
    "Kandla Agro.png",
    "Kopil-Logo-1.jpg",
    "Kush.png",
    "Man_Industries_Logo-new.jpg",
    "Manaksia.png",
    "Max_Fashion_and_Accessories,_March_2018.png",
    "Meghmani Dyes.jpg",
    "Mircle.png",
    "Mono.png",
    "Morgan.gif",
    "Mubea.jfif",
    "NANDA-FEEDS logo.webp",
    "NY.jpg",
    "Nalco.jpg",
    "Parikh.png",
    "Pirama.png",
    "Prism.png",
    "RE craft.jfif",
    "Radiant.png",
    "Ramco-Industries-Ltd-logo.png",
    "Reliance-Retail-Limited.jpg",
    "Ruchi Foods.jpg",
    "SSF.PNG",
    "Sainest-Logo1.png",
    "Schmetz_Logo_Vertikal.png",
    "Shaily Engineering Plastics Limited 2.jpg",
    "Shiva Pharma.png",
    "Shreeji.png",
    "Solaris.jpg",
    "Sumilon.png",
    "TMC.png",
    "Tega.png",
    "United Insulation.jfif",
    "United.png",
    "Wabtec_Logo.svg.png",
    "Woco.JPG",
    "auto-neum-logo.png",
    "canpac.jfif",
    "citizenmetalloyslimited_logo.jfif",
    "credogroup.jpg",
    "ekc logo.png",
    "indian_metal_solutions_logo.jfif",
    "inox-india-private-limited.png",
    "jtpl-logo.jpg",
    "mahadev.jfif",
    "meghmani organic.jfif",
    "meghmani.jfif",
    "mothersongroup_logo.jfif",
    "nippon-ply-.jpg",
    "own.png",
    "plastic-omnium.jpg",
    "rio clay.png",
    "satyesh-brine-logo-1.png",
    "sophos-1024x382.png",
    "speedy_multimodes_limited_logo.jfif",
    "sumito.jfif",
    "surya roshni.jpg",
    "tirupati.jfif",
    "vishakha.jfif",
    "zydus_life_logo.jpg"
];
